import Head from 'next/head';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { FaFileContract, FaDesktop, FaBan, FaShieldAlt, FaGavel, FaEnvelope } from 'react-icons/fa';

const SITE_URL = 'https://rankresult.in';
const SITE_NAME = 'RankResult';
const LAST_UPDATED = '15 July 2026';

const sections = [
  {
    icon: FaFileContract,
    title: '1. Grant of License',
    content: [
      'This End User License Agreement ("EULA") is a legal agreement between you ("User" or "Licensee") and RankResult Technologies ("Licensor") for the use of the RankResult web platform and its associated services.',
      'Subject to your compliance with this EULA and the Terms of Service, RankResult grants you a non-exclusive, non-transferable, revocable, limited license to access and use the Platform for personal, non-commercial purposes.',
      'This license does not permit you to:',
      '',
      'Sell, rent, lease, sublicense, distribute, or otherwise transfer the Platform or any portion thereof.',
      'Use the Platform for any commercial purpose without our prior written consent.',
      'Modify, adapt, reverse engineer, decompile, or create derivative works from the Platform.',
      'Remove or alter any copyright, trademark, or proprietary notices on the Platform.',
    ],
  },
  {
    icon: FaDesktop,
    title: '2. Ownership',
    content: [
      'The Platform, including all content, features, functionality, code, design, graphics, databases, and underlying technology, is the exclusive property of RankResult Technologies and its licensors.',
      'The Platform is protected by Indian and international copyright, trademark, patent, trade secret, and other intellectual property laws.',
      'This EULA does not transfer any ownership rights to you. All rights not expressly granted are reserved by RankResult Technologies.',
    ],
  },
  {
    icon: FaBan,
    title: '3. Restrictions',
    content: [
      'You shall not, and shall not permit any third party to:',
      '',
      'Use the Platform for any illegal, fraudulent, or unauthorized purpose.',
      'Attempt to gain unauthorized access to any part of the Platform, its servers, or databases.',
      'Introduce viruses, Trojan horses, worms, logic bombs, or other malicious material.',
      'Use any robot, spider, scraper, or other automated means to access the Platform for any purpose.',
      'Interfere with or disrupt the integrity or performance of the Platform.',
      'Use the Platform to develop a competing product or service.',
      'Copy, reproduce, or distribute any portion of the Platform without our written permission.',
    ],
  },
  {
    icon: FaShieldAlt,
    title: '4. Updates & Modifications',
    content: [
      'RankResult may, at its sole discretion, release updates, patches, or modifications to the Platform. These may be automatically deployed without prior notice to you.',
      'We reserve the right to modify, suspend, or discontinue any aspect of the Platform at any time, with or without notice.',
      'We are not liable to you or any third party for any modification, suspension, or discontinuation of the Platform.',
    ],
  },
  {
    icon: FaGavel,
    title: '5. Termination',
    content: [
      'This EULA is effective from the date you first access the Platform and continues until terminated.',
      'The license granted under this EULA will automatically terminate if you fail to comply with any of its terms.',
      'Upon termination, you must cease all use of the Platform and destroy any copies of Platform materials in your possession.',
      'RankResult reserves the right to terminate or suspend your access to the Platform at any time, without notice, for any reason, including violation of this EULA or our Terms of Service.',
      'Sections 2, 3, 5, 6, and 7 shall survive any termination of this EULA.',
    ],
  },
  {
    icon: FaShieldAlt,
    title: '6. Disclaimer of Warranties',
    content: [
      'THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTY OF ANY KIND. RANKRESULT TECHNOLOGIES EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.',
      'RankResult does not warrant that:',
      '',
      'The Platform will meet your specific requirements.',
      'The Platform will be uninterrupted, timely, secure, or error-free.',
      'The results or scores generated by the Platform will be accurate or reliable.',
      'Any errors or defects in the Platform will be corrected.',
    ],
  },
  {
    icon: FaGavel,
    title: '7. Limitation of Liability',
    content: [
      'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL RANKRESULT TECHNOLOGIES, ITS DIRECTORS, OFFICERS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO:',
      '',
      'Your use or inability to use the Platform.',
      'Any unauthorized access to or alteration of your data.',
      'Any inaccurate score, rank, or percentile calculations.',
      'Any content obtained through the Platform.',
      'Any statements or conduct of any third party on the Platform.',
      '',
      'OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING UNDER THIS EULA SHALL NOT EXCEED THE AMOUNT YOU HAVE PAID US IN THE 12 MONTHS PRECEDING THE CLAIM.',
    ],
  },
  {
    icon: FaGavel,
    title: '8. Governing Law',
    content: [
      'This EULA shall be governed by and construed in accordance with the laws of India. Any disputes arising under or relating to this EULA shall be subject to the exclusive jurisdiction of the courts in New Delhi, India.',
    ],
  },
  {
    icon: FaFileContract,
    title: '9. Entire Agreement',
    content: [
      'This EULA, together with our Terms of Service and Privacy Policy, constitutes the entire agreement between you and RankResult Technologies regarding your use of the Platform and supersedes all prior agreements and understandings.',
      'If any provision of this EULA is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.',
    ],
  },
  {
    icon: FaEnvelope,
    title: '10. Contact',
    content: [
      'If you have any questions about this EULA, please contact us:',
      '',
      'Email: support@rankresult.in',
      'Website: rankresult.in',
    ],
  },
];

export default function EULAPage() {
  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: SITE_URL },
      { '@type': 'ListItem', position: 2, name: 'EULA', item: `${SITE_URL}/eula` },
    ],
  };

  return (
    <>
      <Head>
        <title>End User License Agreement (EULA) - RankResult.in | Score Calculator &amp; Rank Predictor</title>
        <meta name="description" content="RankResult End User License Agreement governing the use of our web platform, score calculator, and rank predictor services." />
        <meta name="keywords" content="RankResult EULA, end user license agreement, software license, terms of use" />
        <link rel="canonical" href={`${SITE_URL}/eula`} />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="End User License Agreement (EULA) - RankResult.in" />
        <meta property="og:description" content="Terms of end user license agreement for RankResult platform." />
        <meta name="robots" content="index, follow" />
        <meta property="og:title" content="End User License Agreement | RankResult" />
        <meta property="og:description" content="Legal agreement governing the use of RankResult platform and services." />
        <meta property="og:url" content={`${SITE_URL}/eula`} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      </Head>

      <div className="min-h-screen bg-[#0a0a0f] text-gray-300">
        <nav className="border-b border-gray-800 bg-[#0a0a0f]/80 backdrop-blur-md sticky top-0 z-50">
          <div className="max-w-7xl mx-auto px-4 h-14 flex items-center justify-between">
            <Link href="/" className="text-lg font-black gradient-text">⚡ RankResult</Link>
            <Link href="/" className="text-xs text-gray-500 hover:text-gray-300 transition">← Back to Home</Link>
          </div>
        </nav>

        <section className="max-w-4xl mx-auto px-4 py-12 md:py-16 text-center">
          <motion.h1 initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="text-3xl md:text-4xl font-black text-white mb-3">
            End User License Agreement
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }} className="text-gray-500 text-sm mb-2">
            Last Updated: {LAST_UPDATED}
          </motion.p>
          <motion.p initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="text-gray-500 text-sm max-w-2xl mx-auto leading-relaxed">
            PLEASE READ THIS END USER LICENSE AGREEMENT CAREFULLY BEFORE USING THE {SITE_NAME} PLATFORM. BY ACCESSING OR USING THE PLATFORM, YOU AGREE TO BE BOUND BY THE TERMS OF THIS EULA.
          </motion.p>
        </section>

        <section className="max-w-4xl mx-auto px-4 pb-16">
          <div className="space-y-6">
            {sections.map(({ icon: Icon, title, content }, i) => (
              <motion.div key={i} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.04 }} className="bg-gray-900/40 border border-gray-800 rounded-xl p-6 md:p-8">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-lg bg-blue-900/40 border border-blue-800/30 flex items-center justify-center shrink-0 mt-1">
                    <Icon className="text-blue-400 text-lg" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h2 className="text-lg font-bold text-gray-200 mb-3">{title}</h2>
                    <div className="text-sm text-gray-400 leading-relaxed space-y-1">
                      {content.map((line, j) => {
                        if (line === '') return <br key={j} />;
                        return <p key={j}>{line}</p>;
                      })}
                    </div>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </section>

        <footer className="border-t border-gray-800 py-8 px-4">
          <div className="max-w-7xl mx-auto text-center text-xs text-gray-700">
            <p>© {new Date().getFullYear()} {SITE_NAME}.in — All Rights Reserved</p>
            <div className="flex flex-wrap justify-center gap-x-4 gap-y-1 mt-2">
              <Link href="/privacy" className="hover:text-gray-400 transition">Privacy Policy</Link>
              <Link href="/terms" className="hover:text-gray-400 transition">Terms of Service</Link>
              <Link href="/disclaimer" className="hover:text-gray-400 transition">Disclaimer</Link>
              <Link href="/cookie-policy" className="hover:text-gray-400 transition">Cookie Policy</Link>
              <Link href="/refund-policy" className="hover:text-gray-400 transition">Refund Policy</Link>
              <Link href="/contact" className="hover:text-gray-400 transition">Contact Us</Link>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}
